### ISSUE TITLE
Extension icon under Resources/Public/Icons/ folder

### ISSUE THREAD

**Issue by instruccionesaldorso** [web-vision/wv_file_cleanup#11]
According to official documentation (see https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ExtensionArchitecture/FilesAndLocations/Index.html#reserved-file-names), extension icon should be under Resources/Public/Icons/Extension.svg.
Would you mind moving it to that location, instead of the root of extension /ext_icon.svg?
We're using helhum/typo3-secure-web composer package, to use public resources under public/ and protect code under private/ and the fact that the icon is not under Resources/Public/Icons makes it not reachable in the Extension Manager.

**Comment by Riiiad** [comment]
Thank you for the feedback it's done in the next release.

**Comment by instruccionesaldorso** [comment]
Thank you, @Riiiad !
