### ISSUE TITLE
[Question] plans to make the extension TYPO3 11 compatible?

### ISSUE THREAD

**Issue by medarob** [web-vision/wv_file_cleanup#12]
Hi,
I found the extension because an editor wanted to know if it is possible in TYPO3 to list all files which are currently unused (not referenced in any TYPO3, custom MASK CE or RTE link) and therefore can be deleted safely. Is this extension suitable for this purpose and will there be a TYPO3 11 compatible version available?

**Comment by DavidBruchmann** [comment]
When installing wv_file_cleanup in TYPO3 version 11 the first error is this:

![image](https://user-images.githubusercontent.com/999146/167803628-59a73118-4ee1-44a4-958a-cda443193e75.png)

It's related to this system change:

- https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/10.2/Deprecation-89577-FALSignalSlotHandlingMigratedToPSR-14Events.html?highlight=signal_postfilemove
- https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/11.0/Breaking-91473-DeprecatedFunctionalityRemoved.html?highlight=signal_postfilemove

**Comment by Riiiad** [comment]
@medarob thank you for your feedback. An 11 LTS compatible version is planned to be released soon.
I will check if it's working with MASK extension and give you an update here.

**Comment by msollmann** [comment]
Any progress on this? :-)

**Comment by Riiiad** [comment]
@msollmann Just merged the changes to master. So it is now compatible with 11 LTS. The Release will follow as we need to do some more testing.

**Comment by msollmann** [comment]
After installing it on v11 there is an error in FileRepository, line 199:

An exception occurred while executing 'SELECT COUNT(`recuid`) FROM `sys_refindex` WHERE (`ref_table` = ?) AND (`ref_uid` = ?) AND (`deleted` = ?) AND (`tablename` <> ?)' with params ["sys_file", 2857, 0, "sys_file_metadata"]: Unknown column 'deleted' in 'where clause'

It seems that table sys_refindex in v11 has no "deleted"-field anymore.

**Comment by DTM-TYPO3** [comment]
Hi,
is there any progress in adapting the extension for Typo3 V11?

**Comment by Riiiad** [comment]
Master is now working with LTS 11. Soon we will release a new version.
